# Gerando arquivo por UF residência

- <a href="http://download.inep.gov.br/microdados/microdados_enem_2019.zip">Link para Donwload direto do site do ENEM;</a>
- Colocar notebook na mesma pasta do aqruivo de 3 GB do enem (Pastas DADOS).<br>
- Colocar **UF** desejado; <br> 
- Executar todos os blocos;<br>
- Dentro da pasta dados será gerado o arquivo '{UF inserida}_MICRODADOS_ENEM_2019.csv'<br>

OBS: o arquivo de 3GB não abre no notepad, abriu depois de longas espera no sublime text
- <a href="http://download.inep.gov.br/microdados/microdados_enem_2019.zip">Link para Donwload direto do site do ENEM;</a>
https://drive.google.com/file/d/1yBXeLoXcUzakAKqNteamzaZjwypErzhe/view?usp=sharing

In [134]:
nome_arquivo = 'MICRODADOS_ENEM_2019.csv'
uf = 'RJ'

In [135]:
import csv

def gerador(arq, uf):
    with open(arq, "r") as csvfile:
        datareader = csv.reader(csvfile)
        yield next(datareader)[0].split(";")      
        for row in datareader:
            if row[0].split(";")[5] == uf:
                yield row[0].split(";")

In [136]:
lista = list(gerador(nome_arquivo,uf ))

In [137]:
len(lista)

338711

In [138]:
import pandas as pd

In [139]:
df = pd.DataFrame(lista)

In [140]:
df.columns = df.loc[0]
df.drop(0, inplace =True )

In [142]:
df

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
1,190001015227,2019,3302056,Italva,33,RJ,32,F,1,3,...,A,A,A,B,B,A,B,A,A,A
2,190001025702,2019,3305109,São João de Meriti,33,RJ,32,M,1,3,...,A,A,A,B,A,A,B,A,A,A
3,190001027285,2019,3304557,Rio de Janeiro,33,RJ,26,M,1,3,...,B,A,A,B,A,A,B,A,B,B
4,190001034993,2019,3304557,Rio de Janeiro,33,RJ,19,F,1,3,...,A,A,A,A,A,A,B,A,A,B
5,190001065566,2019,3304557,Rio de Janeiro,33,RJ,22,F,1,3,...,A,A,A,B,B,A,C,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338706,190006118895,2019,3304557,Rio de Janeiro,33,RJ,18,F,0,3,...,B,A,B,D,A,B,E,B,A,B
338707,190006118896,2019,3305109,São João de Meriti,33,RJ,52,F,2,3,...,A,A,A,B,A,A,B,B,A,A
338708,190006118897,2019,3304557,Rio de Janeiro,33,RJ,23,F,1,1,...,B,A,A,D,B,B,E,A,B,B
338709,190006118898,2019,3300308,Barra do Piraí,33,RJ,32,F,1,2,...,A,A,A,B,B,A,B,A,A,A
338710,190006118899,2019,3304904,São Gonçalo,33,RJ,41,F,0,3,...,B,A,A,B,A,A,C,A,B,B

In [143]:
df.to_csv(uf+"_"+nome_arquivo,sep=";",index=False)